### ISSUE TITLE
Страница расписания

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/moevm#11]
Добавить страницу расписания со следующим видом.
Страница должна быть автоматичечкой (рендерим таблицу, а клетки заполняются по условиям из списка пар)

Информация о паре это название, день недели, преподаватель, время, тип (числитель, знаменатель, каждую неделю).
<img width="667" alt="image" src="https://github.com/reznikovkg/moevm/assets/36205504/4395eba9-d524-433d-b119-906894fffe0b">

**Comment by ShiryaevNikolay** [comment]
У меня идея сделать это с помощью grid. Или есть лучше способ?

**Comment by ShiryaevNikolay** [comment]
Уже есть пример, как будут раниться данные или мне нужно будет самому продумать, какой массив обрабатывать?

**Comment by reznikovkg** [comment]
> У меня идея сделать это с помощью grid. Или есть лучше способ?

Да, лучше всего подойдет grid.

> какой массив обрабатывать?

Условный массив выглядит следующим образом.
https://github.com/cheremiskin/excel-parser
Для примера запустите проект и загрузите файл нашего расписания в xlxs формате

**Comment by ShiryaevNikolay** [comment]
Открыл [ПР](https://github.com/reznikovkg/moevm/pull/13)
