### ISSUE TITLE
Просмотр изображений и модальные окна

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/moevm#16]
Требуется реализовать в проекте модальные окна. Использовать пример с проекта - https://github.com/reznikovkg/bibliography

Логика работы следующая. При клике на картинку (например при просмотре новости) она открывается в модальном окне.
На картинке висит событие клика с открытием модального окна в который передается конфигурация: список изображений и порядоковый номер для показа. Внутри модального окна, если картинок несколько, то доступны функции навигации для переключения картинок.

Таким образом, такую же логику можно использовать при просмотре изображений в галерее. Кликаем любую картинку, открывается окно со всеми доступным и картинками в окружении и их можно просматривать переключаясь

**Comment by Savage-E** [comment]
Подскажите, какой компонент отвечает за авторизацию в проекте в ветке dev?
https://github.com/reznikovkg/bibliography
не могу найти место где задается пароль

**Comment by reznikovkg** [comment]
@Savage-E в проекте нет авторизации. Все работает при локальном разворачивании

**Comment by Savage-E** [comment]
![image](https://github.com/reznikovkg/moevm/assets/62114162/4e089310-a334-4142-94ef-4a06dab8d05d)

**Comment by Savage-E** [comment]
я запускал через npm install serve

**Comment by reznikovkg** [comment]
npm install
npm run serve

Такого быть не должно. У вас локальная блокировка на localhost. Гуглите

**Comment by Savage-E** [comment]
опечатался, я запускал npm run serve

**Comment by Savage-E** [comment]
ок, спасибо, я думал что в проекте авторизация какая то

**Comment by Savage-E** [comment]
![image](https://github.com/reznikovkg/moevm/assets/62114162/1d8c0a13-25b8-4dd8-affb-54a7553f537e)
Насколько нужно запариваться над стилями кнопок?
или так пойдет?

**Comment by reznikovkg** [comment]
По стилям требований нет. Главное - рабочий функционал
