### ISSUE TITLE
Адаптация компонента расписания

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/moevm#18]
Текущая страница расписания отображается таблицей `/schedule`.
В мобильной версии страница выглядит страшно.

Требуется сделать мобильную сетку расписания (новый компонент).
Если сейчас дни расположены по горизонтали, то необходимо сделать по вертикали. Время отмечается для каждого дня. Логика расчета сетки и клеток должна быть иной. 
Показывать мобильную таблицу или обычную, проверяется через класс, который имеет @media ограничение.

**Comment by Savage-E** [comment]
про время не понял, а сейчас разве оно отмечается не для каждого дня?
по вертикали у нас идет время
и про **Логика расчета сетки и клеток должна быть иной.** -  что не так с текущей? или имеется в виду реализовать собственный вариант расчета?

**Comment by Savage-E** [comment]
то есть daycard и lessoncard я не могу использовать?

**Comment by reznikovkg** [comment]
Вам нужно использовать, да, но там есть доп расчеты, куда они устанавливаются отдельно.

Расписание будет выглядеть так:
Понеденьник
8:00 [клетка занятия]
9.45 [клетка занятия]
...
Вторник
8:00 [клетка занятия]
И так далее

**Comment by Savage-E** [comment]
![image](https://github.com/reznikovkg/moevm/assets/62114162/fdf486ca-f970-4483-a9ce-2550eb8d5885)
вот так сделал. пойдет?
