### ISSUE TITLE
Компонент просмотра новости

### ISSUE THREAD

**Issue by reznikovkg** [reznikovkg/moevm#5]
Создать компонент просмотра новости и страницу.

Новости брать из хранилища по id. Страница новостей /news/:id (news/_id.vue)

<img width="445" alt="image" src="https://github.com/reznikovkg/moevm/assets/36205504/47441b3a-7e1d-4188-8b1d-5f5e639d0ad7">

**Comment by Savage-E** [comment]
Мне нужно переиспользовать ArticleCard?

**Comment by reznikovkg** [comment]
@Savage-E нет. Нужен новый компонент

**Comment by Savage-E** [comment]
![image](https://github.com/reznikovkg/moevm/assets/62114162/2f55c7cd-ae5f-48d5-9280-b62c26dd36fd)

Я правильно понимаю, когда мы нажимаем на acrticle card нас перебрасывает на компонент NewsCard(то что я должен создать)?

**Comment by reznikovkg** [comment]
@Savage-E  Да, можно так. Но нужно оборачивать AcrticleCard NuxtLink вне, а не внутри компонента. Сам компонент AcrticleCard менять не нужно
